### ISSUE TITLE
2016 and 2017 vods are semi broken

### ISSUE THREAD

**Issue by ghost** [mikaelssen/Jefmajor.com#12]
the codec of most of the vods seems to be missing some time data and thus the browser wont play them. the work around for now is to play them directly through vlc with the url.

will look into intergrating a web player.

**Comment by ghost** [comment]
Error lies with FFMPEG and Youtube-DL, somehow it's forgetting the 'time atoms' for the MP4 file format, the workaround for this is to use VLC media player on the broken URL's, and the VOD will play.

Suggestions would be highly appreciated.

**Comment by ghost** [comment]
Making changes to the vod storage system internally right now. and will see if i can get a better NginX streaming plugin on the job. That might correct the issue of semi derp mp4 files.

**Comment by ghost** [comment]
This was put on ice, will actually take a look at the QNAP transcoding systems and see if they can do an automatic recode of them 👍

**Comment by ca-d** [comment]
https://handbrake.fr/features.php

:+1:

**Comment by ghost** [comment]
I mean, yes, thanks, just need a fancy script then 👍 

Edit: will try QNAP first though, i just enabled it, we'll see what it does :^)

**Comment by ghost** [comment]
Good news. transcoding seems to work.
Bad news. twice the vids for now :^) so time to prune and get a real sysyem going.
