### ISSUE TITLE
Website is having issues?

### ISSUE THREAD

**Issue by SailorJerrys** [mikaelssen/Jefmajor.com#13]
Unsure of the causes, but jefmajor.com works fine, but going to vods gives a QNAP "Page not found or webserver is currently unavailable."

The servers been up and down the last day or two, keeps giving errors like that and then fixing itself (or someones fixing them) and then getting the problems again. Apologies if this isn't the right place to be posting this kind of error!

**Comment by ghost** [comment]
its missing a symlink atm, due to me doing a massive move yesterday to a new host system. it will be functional later today. 

thanks for reporting though. :)

**Comment by ghost** [comment]
Issue should have been resolved now, will go down briefly while i physically move the box later, SSL cert was invalid now, so we're simply going to go with plain http for now. Enjoy your vods

also if one refuses to play, then put the mp4 link into vlc and it should work 99% of the time 👍
