### ISSUE TITLE
Resize issue below 1080p / mobile for the background not being dynamic

### ISSUE THREAD

**Issue by ghost** [mikaelssen/Jefmajor.com#2]
The Javascript file animating the background could use a lot of work really, or a complete rewrite.
It's sample code from the intertubes, and it does not scale dynamically, so rip mobiles.

So there's an opportunity there if someone wants to create some dank 3d / 2d or multiple backgrounds even. 
Unless they/you/robots edit the main layout, 'cause by all means, do :+1:

**Comment by NaakkaDev** [comment]
Would you mind if I almost completely rewrite the html/css (maybe even js)? The site would magically be responsive (look good on mobile, etc) after that without really changing the current look.

**Comment by ghost** [comment]
As long as it keeps the value, then sure, just don't make it "html5" styled scroll down shit, and actually professional looking.
