### ISSUE TITLE
Ignoring vods

### ISSUE THREAD

**Issue by knyghty** [mikaelssen/Jefmajor.com#6]
I noticed it in the description, so...

You can make a `.gitignore` file in the Vods directory, that'll override anything in the main `.gitignore` (anything in the main one still carries over though). So in that `.gitignore`, you can just ignore the filetypes you want, and it'll go deeper into the directory structure but won't traverse upwards.

I would create a PR for it but the dir isn't in the repo, so...

**Comment by ghost** [comment]
So adding this `.gitignore` containing 
`**/*.mp3
**/*.mp4
**/*.avi
**/*.mkv
**/*.js
**/*.jpg
**/*.flv
**/*.zip` Should theoretically work? With recursive results.

**Comment by knyghty** [comment]
Aye. If you remove the project level gitignore and stick that into `Vods` you should be good.

Not sure if you need all the asterisks, I think something like this should work:

```
*.mp3
*.mp4
...
```

But you can try it locally, `git add .` and `git status` and you can see all the files that will be added.

**Comment by ghost** [comment]
did so, and working on it at this very moment, found a lot of weird formats in there like .xspf

**Comment by ghost** [comment]
Push seems clear, the directory system here is literally 3 years old, so it contains terrible code. :+1: if there's nothing more i'd consider this issue closed in 24/hrs
