### ISSUE TITLE
Use -o option on youtube-dl for custom format

### ISSUE THREAD

**Issue by KyleSiefring** [mikaelssen/Jefmajor.com#7]
I use `-o '%(id)s__%(upload_date)s__%(title)s.%(ext)s'` when I download vods. This makes them chronologically ordered when sorted alphabetically.

**Comment by ghost** [comment]
Can also just add a sort option by file creation, and it would work just as well?

**Comment by KyleSiefring** [comment]
I'm not sure if all common file systems keep that data. I'm pretty sure ext4 doesn't. If somebody wants to download a bunch of them it could be a problem.

It would help on the web page if you could set it up.

**Comment by ghost** [comment]
the ID format, or the TimeStamps? 'cause the HTTP transfer probably won't send that metadata no, but i'd rather not edit the Naming format we've had for the past 2 years now though. I'll tag this as a feature request i guess?

**Comment by KyleSiefring** [comment]
It should be trivial to convert all the vods to id-title from title-id format so that is something to consider.

**Comment by ghost** [comment]
Will rename the vods after a regex solution has been found, not manually renaming 2 years of vods..

**Comment by ghost** [comment]
Renamed all VOD's (2015 and 2016 folder) to {ID - Title.Ext} format, they're now sorted from oldest to newest.

Newer Vods will use this `-o '%(id)s - %(title)s.%(ext)s'` 

Acceptable?
